language: php

php:
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - psql -c 'create database laravelph_test;' -U postgres
  - psql -c "CREATE USER homestead WITH PASSWORD 'secret';" -U postgres

script: vendor/bin/phpunit --verbose

addons:
  postgresql: "9.3"
